CREATE TABLE `events` (
	`id` int AUTO_INCREMENT NOT NULL,
	`title` varchar(255) NOT NULL,
	`description` text NOT NULL,
	`category` varchar(100) NOT NULL,
	`subcategory` varchar(100),
	`tags` text,
	`latitude` varchar(50) NOT NULL,
	`longitude` varchar(50) NOT NULL,
	`location` varchar(255) NOT NULL,
	`borough` varchar(100),
	`eventDate` timestamp NOT NULL,
	`videoUrl` varchar(500),
	`imageUrl` varchar(500),
	`source` varchar(255),
	`verified` boolean NOT NULL DEFAULT false,
	`createdBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `events_id` PRIMARY KEY(`id`)
);
